ci:
  autofix_commit_msg: "🚨 通过预提交挂钩自动修复"
  autofix_prs: true
  autoupdate_branch: main
  autoupdate_schedule: monthly
  autoupdate_commit_msg: "⬆️ 自动更新预提交挂钩"
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        stages: [pre-commit]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black
        stages: [pre-commit]
